spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

wutsi:
  client-id: "wutsi-payment"
  platform:
    security:
      type: "jwt"
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
    stream:
      rabbitmq:
        url: ${CLOUDAMQP_URL}

