spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

wutsi:
  platform:
    payment: # IMPORTANT: ONLY FLUTTERWAVE USED IN TEST
      mtn:
        enabled: false
      orange:
        enabled: false
      flutterwave:
        enabled: true
        secret-key: ${FLUTTERWAVE_SECRET_KEY}
    security:
      api-key: ${API_KEY}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}

