ALTER TABLE T_TRANSACTION ADD COLUMN expires TIMESTAMPTZ;
ALTER TABLE T_TRANSACTION ADD COLUMN approved TIMESTAMPTZ;
ALTER TABLE T_TRANSACTION ADD COLUMN requires_approval BOOLEAN NOT NULL DEFAULT false;
