ALTER TABLE T_TRANSACTION ADD COLUMN from_account_fk BIGINT REFERENCES T_ACCOUNT(id);
ALTER TABLE T_TRANSACTION ADD COLUMN to_account_fk BIGINT REFERENCES T_ACCOUNT(id);
ALTER TABLE T_TRANSACTION ALTER COLUMN payment_method_token DROP NOT NULL;
