openapi: "3.0.0"
info:
  title: "Wutsi Payment API"
  description: |
    API for managing payments.
    This API allows to
    - Cash in: Move money from owner's account into the wallet
    - Cash out: Move monet from wallet to owner's account
    - Transfer: Transfer money between wallets
  version: "1.0.0"

servers:
  - url: https://wutsi-payment-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-payment-server-prod.herokuapp.com
    description: Production

paths:
  /v1/transactions/cashins:
    post:
      operationId: "create-cashin"
      description: Cash-in money
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCashinRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCashinResponse'
        409:
          description: The operation failed
      tags:
        - Transactions
      security:
        - api_key: [ 'payment-manage' ]

  /v1/users/{user-id}/account:
    get:
      operationId: "get-user-account"
      description: Find account of a user
      parameters:
        - in: path
          name: user-id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
      tags:
        - Account
      security:
        - api_key: [ 'payment-read' ]

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreateCashinRequest:
      type: object
      properties:
        paymentMethodToken:
          type: string
          description: Token of the payment method from where the money will be transfered from.
        amount:
          type: number
          format: double
          description: Amout to transfer to the user's wallet
          minimum: 0
        currency:
          type: string
          description: 3 letter currency code
          maxLength: 3
      required:
        - paymentMethodToken
        - currency

    CreateCashinResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the charge created
        status:
          description: Status of the charge
          type: string
          enum:
            - PENDING
            - SUCESS

    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the account
        type:
          type: string
          description: Type of account
          enum:
            - REVENU
            - LIABILITY
        name:
          type: string
          description: Name of the owner
          nullable: true
        balance:
          type: number
          format: double
          description: Balance of the account
        currency:
          type: string
          description: 3 letter currency code
        created:
          type: string
          description: Creation data-time
          format: date-time

    GetAccountResponse:
      type: object
      properties:
        account:
          type: object
          $ref: "#/components/schemas/Account"
