openapi: "3.0.0"
info:
  title: "Wutsi Payment API"
  description: |
    API for managing payment
  version: "1.0.0"

servers:
  - url: https://wutsi-payment-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-payment-server-prod.herokuapp.com
    description: Production

paths:
  /v1/charges:
    post:
      operationId: "create-charge"
      description: Charge a customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChargeRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateChargeResponse'
      tags:
        - Charges
      security:
        - api_key: [ 'payment-manage' ]

  /v1/charges/{id}:
    get:
      operationId: "get-charge"
      description: Return a charge information
      parameters:
        - in: path
          name: id
          description: ID of the charge
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetChargeResponse'
      tags:
        - Charges
      security:
        - api_key: [ 'payment-read' ]

  /v1/payouts:
    post:
      operationId: "create-payout"
      description: Charge a Payout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePayoutRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePayoutResponse'
      tags:
        - Charges
      security:
        - api_key: [ 'payment-manage' ]

  /v1/payouts/{id}:
    get:
      operationId: "get-payout"
      description: Return a payout information
      parameters:
        - in: path
          name: id
          description: ID of the payout
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPayoutResponse'
      tags:
        - Payout
      security:
        - api_key: [ 'payment-read' ]

  /v1/balances:
    get:
      operationId: "get-balance"
      description: Return the balance of an account
      parameters:
        - in: query
          name: account-id
          description: ID of the account
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: payment-method-provider
          description: Payment Provider
          required: true
          schema:
            type: string
            enum:
              - MTN
              - ORANGE
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBalanceResponse'
      tags:
        - Balance
      security:
        - api_key: [ 'payment-read' ]

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreateChargeRequest:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
          description: Account ID of the merchant who charges the customer
        applicationId:
          type: integer
          format: int64
          description: ID of the application associated with this transaction
        paymentMethodToken:
          type: string
          description: Payment method used by customer to get charged
        externalId:
          type: string
          description: ID of the product purchased
        description:
          type: string
          description: Description of the transaction
        amount:
          type: number
          format: double
          description: Amout to charge to the customer
          minimum: 0
        currency:
          type: string
          description: 3 letter currency code
          maxLength: 3
      required:
        - paymentMethodToken
        - description
        - currency

    CreateChargeResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the charge created
        status:
          type: string
          description: Status of the charge


    GetChargeResponse:
      type: object
      properties:
        charge:
          type: object
          $ref: "#/components/schemas/Charge"


    GetBalanceResponse:
      type: object
      properties:
        balance:
          type: object
          $ref: "#/components/schemas/Balance"


    CreatePayoutRequest:
      type: object
      properties:
        paymentMethodProvider:
          description: Payment Provider
          type: string
          enum:
            - MTN
            - ORANGE
      required:
        - paymentMethodToken

    CreatePayoutResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the payout created
        status:
          type: string
          description: Status of the payout

    GetPayoutResponse:
      type: object
      properties:
        payout:
          type: object
          $ref: "#/components/schemas/Payout"


    Charge:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the transaction
        userId:
          type: integer
          format: int64
          description: ID of the user who performed the transactions
        merchantId:
          type: integer
          format: int64
          description: Account ID of the merchant who charges the customer
        customerId:
          type: integer
          format: int64
          description: Account ID of the customer who get charged
        applicationId:
          type: integer
          format: int64
          description: ID of the application associated with this transaction
          nullable: true
        paymentMethodToken:
          type: string
          format: uuid
          description: Payment method used by customer to get charged
        externalId:
          type: string
          description: ID of the product purchased
        description:
          type: string
          description: Description of the transaction
        amount:
          type: number
          format: double
          description: Amout to charge to the customer
        gatewayTransactionId:
          type: string
          description: Transaction ID
        financialTransactionId:
          type: string
          description: Financial Transaction ID
          nullable: true
        currency:
          type: string
          description: 3 letter currency code
        status:
          type: string
          description: Transaction status
          enum:
            - PENDING
            - SUCESSFUL
            - FAILED
        errorCode:
          type: string
          description: Error code
          nullable: true
        supplierErrorCode:
          type: string
          description: Error Details
          nullable: true
        paymentMethodType:
          type: string
          description: Type of payment method
          enum:
            - MOBILE_PAYMENT
        paymentMethodProvider:
          type: string
          description: Payment provider
          enum:
            - MTN
            - ORANGE
        created:
          type: string
          format: date-time
          description: Creation Date/Time
        updated:
          type: string
          format: date-time
          description: Last modification Date/Time

    Balance:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
          description: ID of account
        paymentMethodProvider:
          type: string
          description: Payment provider
          enum:
            - MTN
            - ORANGE
        amount:
          type: number
          format: double
          description: Amout to charge to the customer
        currency:
          type: string
          description: 3 letter currency code
        synced:
          type: string
          format: date
          description: Last synchornization date

    Payout:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the transaction
        userId:
          type: integer
          format: int64
          description: ID of the user who performed the transactions
          nullable: true
        accountId:
          type: integer
          format: int64
          description: ID of the account from where the payout will be done
        description:
          type: string
          description: Description of the transaction
        gatewayTransactionId:
          type: string
          description: Transaction ID
        financialTransactionId:
          type: string
          description: Financial Transaction ID
          nullable: true
        amount:
          type: number
          format: double
          description: Amout to charge to the customer
        currency:
          type: string
          description: 3 letter currency code
          maxLength: 3
        status:
          type: string
          description: Status of the payout
        errorCode:
          type: string
          description: Error code
          nullable: true
          enum:
            - PENDING
            - SUCESSFUL
            - FAILED
        supplierErrorCode:
          type: string
          description: Error Details
          nullable: true
        paymentMethodProvider:
          type: string
          description: Payment provider
          enum:
            - MTN
            - ORANGE
        created:
          type: string
          format: date-time
          description: Creation Date/Time
        updated:
          type: string
          format: date-time
          description: Last modification Date/Time
